apiVersion: v1
kind: Service
metadata:
  labels:
    app: l1
  name: l1
spec:
  type: LoadBalancer
  ports:
    - name: "8545"
      port: 8545
      targetPort: 8545
    - name: "8546"
      port: 8546
      targetPort: 8546
  selector:
    app: l1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: l1
  name: l1
spec:
  replicas: 1
  serviceName: l1
  selector:
    matchLabels:
      app: l1
  template:
    metadata:
      labels:
        app: l1
    spec:
      containers:
        - image: kfangw/ops-bedrock_l1
          name: l1
          ports:
            - containerPort: 8545
            - containerPort: 8546
          resources: {}
          volumeMounts:
            - mountPath: /db
              name: l1-data
            - mountPath: /repo
              name: git-repository
            - mountPath: /config
              name: config
          env:
            - name: GENESIS_FILE_PATH
              value: "/repo/genesis/devnet-20230216-0/genesis-l1.json"
      initContainers:
        - name: init
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/iskraworld/optimism-ops
            - /repo
          volumeMounts:
            - mountPath: /repo
              name: git-repository
        - name: init2
          image: alpine
          command: ["/bin/sh"]
          args:
            - -c
            - cp /repo/secrets/test-jwt-secret.txt /config/test-jwt-secret.txt
          volumeMounts:
            - mountPath: /repo
              name: git-repository
            - mountPath: /config
              name: config
      volumes:
        - name: git-repository
          emptyDir: {}
        - name: config
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: l1-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
