---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: l2
  name: l2
spec:
  type: LoadBalancer
  ports:
    - name: "8545"
      port: 8545
      targetPort: 8545
    - name: "9545"
      port: 9545
      targetPort: 8545
    - name: "8551"
      port: 8551
      targetPort: 8551
  selector:
    app: l2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: l2
  name: l2
spec:
  replicas: 1
  serviceName: l2
  selector:
    matchLabels:
      app: l2
  template:
    metadata:
      labels:
        app: l2
    spec:
      containers:
        - command:
            - /bin/sh
            - /entrypoint.sh
            - --authrpc.jwtsecret=/config/test-jwt-secret.txt
          image: kfangw/ops-bedrock_l2
          name: l2
          ports:
            - containerPort: 8545
            - containerPort: 8551
          resources: {}
          volumeMounts:
            - mountPath: /db
              name: l2-data
            - mountPath: /repo
              name: git-repository
            - mountPath: /config
              name: config
          env:
            - name: GENESIS_FILE_PATH
              value: "/repo/genesis/devnet-20230216-0/genesis-l2.json"
      initContainers:
        - name: init
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/iskraworld/optimism-ops
            - /repo
          volumeMounts:
            - mountPath: /repo
              name: git-repository
        - name: init2
          image: alpine
          command: ["/bin/sh"]
          args:
            - -c
            - cp /repo/secrets/test-jwt-secret.txt /config/test-jwt-secret.txt
          volumeMounts:
            - mountPath: /repo
              name: git-repository
            - mountPath: /config
              name: config
      volumes:
        - name: git-repository
          emptyDir: {}
        - name: config
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: l2-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
