apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::079445910763:role/AmazonEKSNodeRole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::079445910763:user/jyeon.kim
      username: jy
kind: ConfigMap
metadata:
  creationTimestamp: "2023-02-09T02:37:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1517"
  uid: 8b5a7b32-176a-424e-9347-fe0c63007272
